name = techblox_recipes
description = Custom crafting recipes and balancing for the Techblox server.
depends = techblox, magic_materials, default, forgotten_monsters, ethereal_bosses, enderpearl, animalia
author = jolethen
